export const launcherTexts:  Record<string, string> = {
    PRESENTATION: "TEXTE MANQUANT",
    STEP1: "Votre vaisseau mesure 142 mètres de haut pour une masse de 5200 tonnes. Faire décoller votre vaisseau depuis la Terre est un défi colossal.\nBonus COOP – Intelligence artificielle de supervision d’IA.\nLa coordination des IA du vaisseau facilite la gestion de l’énergie et la priorisation des tâches.",
    STEP2: "Pour atteindre Europe en 6 ans, vous devez atteindre la vitesse de 20 km/s (72 000 km/h). Utilisez la manœuvre la moins couteuse : l’assistance gravitationnelle. Profitez de la force d’attraction de Vénus pour accélérer votre vaisseau. Pendant cette manœuvre près de Vénus vous perdez la communication avec le centre de commande de la Terre.\nBonus COOP – Centre de commandement virtuel embarqué.\nUn centre de commandement virtuel vous accompagnera dans la prise de décision, coupés de toutes communication avec la Terre.",
    STEP3: "Dans votre trajectoire elliptique, vous repassez près de la Terre pour récupérer eau, air et nourriture. Amarrez à votre vaisseau à pleine vitesse un cargo de ravitaillement.\nBonus MECA – Pilotage en réalité virtuelle\nUne interface de pilotage en réalité virtuelle facilite la prise en charge de l’amarrage.",
    STEP4: "Une tempête solaire menace votre vaisseau. Les puissantes radiations peuvent endommager les systèmes électroniques et la santé des astronautes : Préparez-vous y pour limiter les dégâts !\nBonus AERO – Automatisation du bouclier magnétique\nLe bouclier magnétique permet de dévier une partie des radiations.\nBonus EXPE – Combinaison adaptative de sortie extravéhiculaire\nDes combinaisons adaptées réduisent l’impact des radiations sur le corps des astronautes.",
    STEP5: "Après deux ans de voyage, vous arrivez aux abords de la ceinture d’astéroïdes. Les gros astéroïdes seront facilement évitables, mais les plus petits sont imprévisibles. Limitez les dégâts causés par leur impact à 72 000 km/h.\nBonus AERO – Bras robotisé autonome de réparation\nUn bras robotique permet de réparer les dégâts externes et de repousser les petits astéroïdes lors de la traversée.\nBonus EXPE – Cobot d’exploration\nLes cobots facilitent les réparations des dégâts interne au vaisseau subis lors de la traversée en accompagnant les astronautes.",
    STEP6: "Après plus de trois ans de voyage, l’équipage, confiné les uns sur les autres les uns sur les autres dans un environnement confiné et stressant. Le problème que vous rencontrez est cette fois-ci interne au vaisseau. Des tensions apparaissent au sein de l’équipage, mettant la mission en danger.\nBonus MEDI – Activités collectives pour la cohésion de groupe\nDes systèmes favorisant les interactions sociales, compte tenu des préférences de chacun aident à apaiser les tensions sociales et à recréer du lien.\nBonus GECO – Plantes utiles au bien-être de l’équipage\nUn environnement végétalisé ainsi qu’une assiette variée permet de remonter le moral de l’équipage et d’apaiser les tensions.",
    STEP7: "Après plus de quatre ans de recyclage biologique continu, des déséquilibres apparaissent dans l’air, l’eau et les micro-organismes (maladies). Assainissez votre environnement.\nBonus GECO – Système mécanique de recyclage de secours.\nUn système mécanique de recyclage aide à compenser les manquements des systèmes biologiques pour stabiliser les paramètres de l’environnement.\nBonus MEDI – Suivi des souches bactériennes.\nUn système de veille sanitaire permet d’éviter le développement de maladies bactériologiques ou virales.",
    STEP8: "Après 6 ans de voyage, vous vous installez enfin en orbite d’Europe. Depuis la Terre, nous n’avons pu qu’estimer les conditions à la surface et dans les profondeurs d’Europe. Afin d’adapter vos plans à la réalité de terrain, envoyez une flotte robotique d’exploration.\nBonus MECA – Robots mous adaptés à l’exploration.\nDes robots mous spécialisés dans la collecte de données topographiques et climatiques vous facilitera la collecte de données."
} as const;